// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ApplicationController from "./application_controller"
application.register("application", ApplicationController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import HomeController from "./home_controller"
application.register("home", HomeController)

import ImageModalController from "./image_modal_controller"
application.register("image-modal", ImageModalController)

import SortableController from "./sortable_controller"
application.register("sortable", SortableController)

import TomSelectController from "./tom_select_controller"
application.register("tom-select", TomSelectController)
