apiVersion: v1
kind: Namespace
metadata:
  name: web
---
apiVersion: v1
kind: Secret
metadata:
  name: portfolio-secret
  namespace: web
type: Opaque
data:
  secret-key-base: SECRET_KEY_BASE_SECRET
  rails-master-key: RAILS_MASTER_KEY_SECRET
  postgres-db: POSTGRES_DB_SECRET
  postgres-user: POSTGRES_USER_SECRET
  postgres-password: POSTGRES_PASSWORD_SECRET
  postgres-host: POSTGRES_HOST_SECRET
  postgres-port: POSTGRES_PORT_SECRET
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: portfolio-pv
  namespace: web
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/portfolio
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: portfolio-pvc
  namespace: web
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-deployment
  namespace: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
      - name: portfolio
        image: gary113/portfolio:latest
        ports:
        - containerPort: 3000
        env:
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: portfolio-secret
              key: secret-key-base
        - name: RAILS_MASTER_KEY
          valueFrom:
            secretKeyRef:
              name: portfolio-secret
              key: rails-master-key
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: portfolio-secret
              key: postgres-db
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: portfolio-secret
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: portfolio-secret
              key: postgres-password
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: portfolio-secret
              key: postgres-host
        - name: POSTGRES_PORT
          valueFrom:
            secretKeyRef:
              name: portfolio-secret
              key: postgres-port
        - name: RAILS_LOG_LEVEL
          value: info
        volumeMounts:
        - name: portfolio-storage
          mountPath: /rails/storage
      volumes:
      - name: portfolio-storage
        persistentVolumeClaim:
          claimName: portfolio-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
  namespace: web
spec:
  selector:
    app: portfolio
  ports:
    - protocol: TCP
      port: 3000
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portfolio-ingress
  namespace: web
spec:
  rules:
  - host: portfolio.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: portfolio-service
            port: 
              number: 3000
