name: Build docker image, push and create release

on:
  push:
    branches:
      - main

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.bump_version.outputs.NEW_TAG }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get repository name
      run: |
        REPO_NAME=${GITHUB_REPOSITORY#*/}
        echo "Repository name: $REPO_NAME"
        echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV

    - name: Get the current version tag
      run: |
        git fetch --tags
        TAG=$(git tag --sort=-v:refname | head -n 1)
        if [ -z "$TAG" ]; then
          TAG="v0.0.1"
        else
          TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
        fi
        echo "Current version: $TAG"
        echo "CURRENT_TAG=$TAG" >> $GITHUB_ENV

    - name: Bump version
      run: |
        VERSION=${{ env.CURRENT_TAG }}
        VERSION_NUMBER="${VERSION#v0.0.}"
        NEW_VERSION_NUMBER=$((VERSION_NUMBER + 1))
        NEW_TAG="v0.0.$NEW_VERSION_NUMBER"
        echo "New version: $NEW_TAG"
        echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
        echo "NEW_TAG=$NEW_TAG" >> $GITHUB_OUTPUT

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO_NAME }}:latest
          ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO_NAME }}:${{ env.NEW_TAG }}
        push: true

  create-release:
    runs-on: ubuntu-latest
    needs: build-and-push-docker-image

    steps:
    - name: Create Release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ needs.build-and-push-docker-image.outputs.new_tag }}
        release_name: "Release ${{ needs.build-and-push-docker-image.outputs.new_tag }}"
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
