name: Build docker image, push and create release

on:
  push:
    branches:
      - master
      - main

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.bump_version.outputs.NEW_TAG }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get the current version tag
      run: |
        git fetch --tags
        TAG=$(git tag --sort=-v:refname | head -n 1)
        if [ -z "$TAG" ]; then
          TAG="v0.0.0"
        fi
        echo "Current version: $TAG"
        echo "CURRENT_TAG=$TAG" >> $GITHUB_ENV

    - name: Bump version
      id: bump_version
      run: |
        VERSION=${{ env.CURRENT_TAG }}
        VERSION_NUMBER="${VERSION#v0.0.}"
        NEW_VERSION_NUMBER=$((VERSION_NUMBER + 1))
        NEW_TAG="v0.0.$NEW_VERSION_NUMBER"
        echo "New version: $NEW_TAG"
        echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
        echo "NEW_TAG=$NEW_TAG" >> $GITHUB_OUTPUT

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        tags: |
          ghcr.io/${{ github.repository }}:latest
          ghcr.io/${{ github.repository }}:${{ env.NEW_TAG }}
        push: true

  create-release-draft:
    runs-on: ubuntu-latest
    needs: build-and-push-docker-image

    steps:
    - name: Delete same draft release if exists
      uses: liudonghua123/delete-release-action@v1
      with:
        release_name: ${{ needs.build-and-push-docker-image.outputs.new_tag }}
        suppress_errors: true
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    - name: Create Release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ needs.build-and-push-docker-image.outputs.new_tag }}
        release_name: ${{ needs.build-and-push-docker-image.outputs.new_tag }}
        draft: true
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
