name: Deploy to cluster

on:
  push:
    tags:
      - 'v0.0.*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get repository name
      run: |
        REPO_NAME=${GITHUB_REPOSITORY#*/}
        echo "Repository name: $REPO_NAME"
        echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV

    - name: Get the current version tag
      run: |
         TAG="${GITHUB_REF#refs/tags/}"
         echo "Current version: $TAG"
         echo "CURRENT_TAG=$TAG" >> $GITHUB_ENV

    - name: Inject secrets
      run: |
        sed -i "s/TAG_VALUE/${{ env.CURRENT_TAG }}/g" .deploy/${{ env.REPO_NAME }}.yaml
        sed -i "s/SECRET_KEY_BASE_VALUE/${{ secrets.SECRET_KEY_BASE }}/g" .deploy/${{ env.REPO_NAME }}.yaml
        sed -i "s/RAILS_MASTER_KEY_VALUE/${{ secrets.RAILS_MASTER_KEY }}/g" .deploy/${{ env.REPO_NAME }}.yaml
        sed -i "s/POSTGRES_DB_VALUE/${{ secrets.POSTGRES_DB }}/g" .deploy/${{ env.REPO_NAME }}.yaml
        sed -i "s/POSTGRES_USER_VALUE/${{ secrets.POSTGRES_USER }}/g" .deploy/${{ env.REPO_NAME }}.yaml
        sed -i "s/POSTGRES_PASSWORD_VALUE/${{ secrets.POSTGRES_PASSWORD }}/g" .deploy/${{ env.REPO_NAME }}.yaml
        sed -i "s/POSTGRES_HOST_VALUE/${{ secrets.POSTGRES_HOST }}/g" .deploy/${{ env.REPO_NAME }}.yaml
        sed -i "s/POSTGRES_PORT_VALUE/${{ secrets.POSTGRES_PORT }}/g" .deploy/${{ env.REPO_NAME }}.yaml
        sed -i "s/HOSTNAME_VALUE/${{ secrets.HOSTNAME }}/g" .deploy/${{ env.REPO_NAME }}.yaml

    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.K3D_SSH_HOST }}
        username: ${{ secrets.K3D_SSH_USERNAME }}
        key: ${{ secrets.K3D_SSH_KEY }}
        port: ${{ secrets.K3D_SSH_PORT }}
        script: kubectl apply -f .deploy/${{ env.REPO_NAME }}.yaml
