name: Build docker image and push

on:
  push:
    branches:
      - dev

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get repository name
      id: get_repo_name
      run: |
        REPO_NAME=${GITHUB_REPOSITORY#*/}
        echo "Repository name: $REPO_NAME"
        echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO_NAME }}:dev
        push: true
